import Head from 'next/head'
import Nav from '../components/nav/index.js'
import Container from '../components/container'
import Hero from '../components/home/hero'
import Footer from '../components/footer'

const Home = () => (
  <>
    <Head>
      <title>Open Process Ventures</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Nav />
    <Container>
      <Hero scrollRef="#footer" />
    </Container>
    <div id="footer">
      <Footer>
        Open Process Ventures is a Web3 specialised investment firm and
        strategic consultancy.
      </Footer>
    </div>
  </>
)

export default Home
